// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	Channel   string             `json:"channel"`
	Recipient string             `json:"recipient"`
	Subject   string             `json:"subject"`
	Body      string             `json:"body"`
	Status    string             `json:"status"`
	SendAt    pgtype.Timestamptz `json:"send_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
