// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    channel,
    recipient,
    subject,
    body,
    status,
    send_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    channel,
    recipient,
    subject,
    body,
    status,
    send_at,
    created_at,
    updated_at,
    sent_at
`

type CreateNotificationParams struct {
	Channel   string             `json:"channel"`
	Recipient string             `json:"recipient"`
	Subject   string             `json:"subject"`
	Body      string             `json:"body"`
	Status    string             `json:"status"`
	SendAt    pgtype.Timestamptz `json:"send_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.SendAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT
    id,
    channel,
    recipient,
    subject,
    body,
    status,
    send_at,
    created_at,
    updated_at,
    sent_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationById(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationById, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}
